### ISSUE TITLE
splash screen when run chrome

### ISSUE THREAD

**Issue by neostfox** [EdisonGates/VN7-591G-Hackintosh_10.15#1]

**Comment by EdisonGates** [comment]
![git](https://user-images.githubusercontent.com/28917870/67730354-c52d5480-fa2f-11e9-850a-66de240029c6.png)
It works fine on my machine, I don't know what you are referring to.

**Comment by neostfox** [comment]
I repaired this but device sleep still can't work

**Comment by neostfox** [comment]
老哥也是中国人啊

**Comment by EdisonGates** [comment]
> 老哥也是中国人啊

是的  中国人
