### ISSUE TITLE
开发者您好，我和您型号一样，已经安装好了，但是内置无线网卡被禁用，之前10.11系统有一个efi可以直接用wifi，但这个不行

### ISSUE THREAD

**Issue by neytao** [EdisonGates/VN7-591G-Hackintosh_10.15#2]
请问这个需要外置什么型号的网卡?

**Comment by neostfox** [comment]
10.13之后好像就没有了无线网卡驱动。

**Comment by neytao** [comment]
那前辈是怎么解决的，是外置什么型号的驱动吗?


 
---原始邮件---
发件人: "neostfox"<notifications@github.com&gt;
发送时间: 2019年11月10日(星期日) 晚上7:45
收件人: "EdisonGates/VN7-591G-Hackintosh_10.15"<VN7-591G-Hackintosh_10.15@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"neytao"<812890717@qq.com&gt;;
主题: Re: [EdisonGates/VN7-591G-Hackintosh_10.15] 开发者您好，我和您型号一样，已经安装好了，但是内置无线网卡被禁用，之前10.11系统有一个efi可以直接用wifi，但这个不行 (#2)



10.13之后好像就没有了无线网卡驱动。

**Comment by neostfox** [comment]
我这边也没搞定，直接用的网线。然后笔记本的休眠都没做好。无奈啊。显卡搞好了2048M，休眠和触摸板都不好使，目前转到Linux了。

**Comment by neytao** [comment]
感谢前辈，不过网线插着体验很不错，谢谢了!


 
---原始邮件---
发件人: "neostfox"<notifications@github.com&gt;
发送时间: 2019年11月10日(星期日) 晚上7:56
收件人: "EdisonGates/VN7-591G-Hackintosh_10.15"<VN7-591G-Hackintosh_10.15@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"neytao"<812890717@qq.com&gt;;
主题: Re: [EdisonGates/VN7-591G-Hackintosh_10.15] 开发者您好，我和您型号一样，已经安装好了，但是内置无线网卡被禁用，之前10.11系统有一个efi可以直接用wifi，但这个不行 (#2)



我这边也没搞定，直接用的网线。然后笔记本的休眠都没做好。无奈啊。显卡搞好了2048M，休眠和触摸板都不好使，目前转到Linux了。

**Comment by neostfox** [comment]
你的触摸板什么的正常吗？

**Comment by neytao** [comment]
触摸板用不了，不过平时没有用触摸板的习惯😂


 
---原始邮件---
发件人: "neostfox"<notifications@github.com&gt;
发送时间: 2019年11月10日(星期日) 晚上8:08
收件人: "EdisonGates/VN7-591G-Hackintosh_10.15"<VN7-591G-Hackintosh_10.15@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"neytao"<812890717@qq.com&gt;;
主题: Re: [EdisonGates/VN7-591G-Hackintosh_10.15] 开发者您好，我和您型号一样，已经安装好了，但是内置无线网卡被禁用，之前10.11系统有一个efi可以直接用wifi，但这个不行 (#2)



你的触摸板什么的正常吗？

**Comment by neostfox** [comment]
休眠呢？我的休眠就是放着那一黑屏就系统直接崩了。

**Comment by neytao** [comment]
哈哈，我也是，我一般不休眠，用就一直亮着，不用就直接关机。


 
---原始邮件---
发件人: "neostfox"<notifications@github.com&gt;
发送时间: 2019年11月10日(星期日) 晚上8:10
收件人: "EdisonGates/VN7-591G-Hackintosh_10.15"<VN7-591G-Hackintosh_10.15@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"neytao"<812890717@qq.com&gt;;
主题: Re: [EdisonGates/VN7-591G-Hackintosh_10.15] 开发者您好，我和您型号一样，已经安装好了，但是内置无线网卡被禁用，之前10.11系统有一个efi可以直接用wifi，但这个不行 (#2)



休眠呢？我的休眠就是放着那一黑屏就系统直接崩了。

**Comment by ShephardChan** [comment]
大佬请问可以发个邮箱吗？我这下载了好多遍都下不了。。。
a659575276@vip.qq.com
感谢感谢！！
