### ISSUE TITLE
#已解决#触摸板问题

### ISSUE THREAD

**Issue by Lynn0605** [EdisonGates/VN7-591G-Hackintosh_10.15#3]
非常感谢作者无私分享EFI，我和你的电脑型号一样，vn7-591，但具体型号是56BD；我尝试驱动HDMI的时候添加了FakePCIID套件，触摸板意外解决了（只能单指，多指据说无解），希望对作者有帮助

**Comment by Lynn0605** [comment]
> 非常感谢作者无私分享EFI，我和你的电脑型号一样，vn7-591，但具体型号是56BD；我尝试驱动HDMI的时候添加了FakePCIID套件，触摸板意外解决了，希望对作者有帮助

**Comment by EdisonGates** [comment]
是的  这款机器的触摸板走的是USB，不是PS2。所以无法驱动多指

**Comment by EdisonGates** [comment]
> 非常感谢作者无私分享EFI，我和你的电脑型号一样，vn7-591，但具体型号是56BD；我尝试驱动HDMI的时候添加了FakePCIID套件，触摸板意外解决了（只能单指，多指据说无解），希望对作者有帮助

是的 这款机器的触摸板走的是USB，不是PS2。所以无法驱动多指

**Comment by tslwoainil** [comment]
能把FakePCIID套件集成进来吗？
顺便问下大哥 OC 引导有考虑过吗？谢谢！

**Comment by Lynn0605** [comment]
> 能把FakePCIID套件集成进来吗？
> 顺便问下大哥 OC 引导有考虑过吗？谢谢！
我尝试用FakePCIID驱动Intel HDMI，但是失败了，因为应用场景不多也就放弃去弄了，你可以新建一个issue问问大佬（作者）

**Comment by Lynn0605** [comment]
> 能把FakePCIID套件集成进来吗？
> 顺便问下大哥 OC 引导有考虑过吗？谢谢！

我尝试用FakePCIID驱动Intel HDMI，但是失败了，因为应用场景不多也就放弃去弄了，你可以新建一个issue问问大佬（作者）

**Comment by EdisonGates** [comment]
> 能把FakePCIID套件集成进来吗？
> 顺便问下大哥 OC 引导有考虑过吗？谢谢！

OC已经集成。我看你已经fork了一份，这份OC不能安装11 bigsur。你应该是知道的 我的触控板给我弄坏了  所以没管这些了

**Comment by tslwoainil** [comment]
我的11 bigsur是用虚拟机安装实体硬盘分区法安装的，测试可以正常使用，oc 6.0 搭配11 bigsur和clover驱动 10.15 一样，非常赞！如你所说，不能安装11 bigsur和ota更新，原因应该是不能进入recovery的缘故，不过已经很赞了！

**Comment by EdisonGates** [comment]
> 我的11 bigsur是用虚拟机安装实体硬盘分区法安装的，测试可以正常使用，oc 6.0 搭配11 bigsur和clover驱动 10.15 一样，非常赞！如你所说，不能安装11 bigsur和ota更新，原因应该是不能进入recovery的缘故，不过已经很赞了！

现在已经更新到可以安装并OTA更新， 可以重新Clone

**Comment by Ityiyong** [comment]
@Lynn0605 大哥，能分享一下你修复好触摸板后的OC EFI吗？ 我原本的CLOVER可以单指触摸板，但是新版的OC引导我不会修复。。。

**Comment by Lynn0605** [comment]
> @Lynn0605 大哥，能分享一下你修复好触摸板后的OC EFI吗？ 我原本的CLOVER可以单指触摸板，但是新版的OC引导我不会修复。。。

**Comment by Lynn0605** [comment]
我当时用的clover,把FakePCIID集成进来后就可以驱动了，你可以尝试将FakePCIID集成到OC中，应该会驱动，我的笔记本触摸板也失灵了hhh,6年多的笔记本该换了
