### ISSUE TITLE
您好，可以直接更新这个吗？

### ISSUE THREAD

**Issue by XavierXuV5** [EdisonGates/VN7-591G-Hackintosh_10.15#4]
![image](https://user-images.githubusercontent.com/18503011/99743992-cb4a1380-2b11-11eb-8b50-2d934c00c8d2.png)

**Comment by EdisonGates** [comment]
可以直接更新，并完美安装。

XavierXu <notifications@github.com> 于 2020年11月20日周五 09:22写道：

**Comment by XavierXuV5** [comment]
好的，谢谢您的回复。

**Comment by tslwoainil** [comment]
大神，该升级OC 6.3 咯！

**Comment by EdisonGates** [comment]
> 大神，该升级OC 6.3 咯！

等几天有时间测试后再上传 ，避免你们直接开不了机。
